name: the_life_list
description: The Life List — a personal birding app powered by eBird.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  geolocator: ^12.0.0
  flutter_map: ^8.3.1
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  flutter_sticky_header: ^0.8.0
  google_fonts: ^8.2.0
  flutter_map_marker_cluster: ^8.2.2
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/loon_icon_flat.png
